### PR TITLE
Implement callable subscripts

### PR DESCRIPTION
**Pull request by markborkum**
Implements `length()` function for JSON arrays, and `entries()`, `keys()` and `values()` functions for JSON objects.

### Description

n/a

### Issues Resolved

n/a

### Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@markborkum I did update the version of pylint on you, since we are supporting Python 3.x only with this we can push pylint beyond 1.x now.

**Comment by markborkum** [comment]
@dmlb2000 Sounds good. I'm working on 100% coverage at the moment. Then I'll circle back to the `pylint` "duplicate-code" warnings.

**Comment by dmlb2000** [comment]
@markborkum There was an interesting duplicate key in hash warning from flake8 as well did you see that?

**Comment by markborkum** [comment]
@dmlb2000 That's resolved by https://github.com/pacifica/python-jsonpath2/pull/14/commits/ea0325b2412893becca38147546d18685568df69. Now we're just left with the "duplicate-code" warnings.

**Comment by markborkum** [comment]
@dmlb2000 I think that we should pause work on this branch.

There are two issues:
1. `pylint` "duplicate-code" warnings; and
2. Coverage of instance methods in ECMAScript standard.

The first issue is what it is, but we need to decide the second issue. At the moment, the coverage is very low.

**Comment by dmlb2000** [comment]
@markborkum What other functions would need to be implemented to cover the ECMAScript standard?

**Comment by markborkum** [comment]
@dmlb2000 The following should be covered:
- Properties, e.g., `length` for JSON arrays and strings.
- Class and instance methods, where: (a) the class is a JSON value; (b) all arguments are JSON values; (c) the return value is a JSON value; and (d) the instance is not mutated.

[Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array):
* [x] length
* [ ] concat
* [ ] entries
* [ ] fill
* [ ] flat
* [ ] includes
* [ ] indexOf
* [ ] join
* [ ] keys
* [ ] lastIndexOf
* [ ] slice
* [ ] sort
* [ ] splice
* [ ] values

[JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON):
* [ ] parse
* [ ] stringify

[Math](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math):
* [ ] abs
* [ ] acos
* [ ] acosh
* [ ] asin
* [ ] asinh
* [ ] atan
* [ ] atan2
* [ ] atanh
* [ ] cbrt
* [ ] ceil
* [ ] clz32
* [ ] cos
* [ ] cosh
* [ ] exp
* [ ] expm1
* [ ] floor
* [ ] fround
* [ ] hypot
* [ ] imul
* [ ] log
* [ ] log10
* [ ] log1p
* [ ] log2
* [ ] max
* [ ] min
* [ ] pow
* [ ] random
* [ ] round
* [ ] sign
* [ ] sin
* [ ] sinh
* [ ] sqrt
* [ ] tan
* [ ] tanh
* [ ] trunc

[Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number):
* [ ] isFinite
* [ ] isInteger
* [ ] isNaN
* [ ] isSafeInteger
* [ ] parseFloat
* [ ] parseInt

[Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object):
* [x] entries
* [x] keys
* [x] values

[String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String):
* [x] charAt
* [ ] codeCharAt
* [ ] codePointAt
* [ ] concat
* [ ] endsWith
* [ ] includes
* [ ] indexOf
* [ ] lastIndexOf
* [x] length
* [ ] localeCompare
* [ ] match
* [ ] normalize
* [ ] padEnd
* [ ] padStart
* [ ] repeat
* [ ] replace
* [ ] search
* [ ] slice
* [ ] split
* [ ] startsWith
* [x] substring
* [ ] toLocaleLowerCase
* [ ] toLocaleUpperCase
* [ ] toLowerCase
* [ ] toUpperCase
* [ ] trim
* [ ] trimEnd
* [ ] trimStart

**Comment by dmlb2000** [comment]
@markborkum This is a lot, we'll leave this open for folks to contribute too and hopefully we can get some community support for this.

Thanks for your effort!

**Comment by markborkum** [comment]
@khm Your thoughts about coverage?

**Comment by khm** [comment]
> @khm Your thoughts about coverage?

I think it would be worth raising an unsupported exception of some kind instead of requiring full coverage as a release condition.  That way we can accept community contributions as need arises.  If I'm answering the wrong question, let me know.

**Comment by dmlb2000** [comment]
@markborkum This is ready to merge?

**Comment by dmlb2000** [comment]
So to be clear for others coming into this bug...

We are going to merge this in, even though the pull request is technically incomplete. This will provide folks with working functions in a jsonpath. The future work is to be explicit about what functions we support and what functions are not completed. We will have future effort to make it easy for folks to add new functions to extend the jsonpath spec. Example pull requests will be referenced here for folks to have a path forward to extend jsonpath.

**Pull request merged**
