### PR TITLE
Add handy shortcut to match string path

### PR DESCRIPTION
**Pull request by dangra**
**[WIP]  Opened to measure acceptance by maintainers. 
Tests and docs will be updated once API is agreed (if any)**

### Description

This change aims to avoid the boilerplate of applying a JsonPath to a document

```python
>>> import jsonpath2 as jsonpath
>>> doc = {'hello': 'Hello, world!'}
>>> [m.current_value for m in jsonpath.match('$["hello"]', doc)]
```

It resembles the use of `re` module in `re.match(pattern, string)` vs `re.compile(pattern).match(string)`

### Issues Resolved

None.

### Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@dangra I think the thought behind this is fine, please make sure the pipeline passes.

**Comment by dmlb2000** [comment]
@dangra can you make a test to cover the code? either add the call to https://github.com/pacifica/python-jsonpath2/blob/2d74af236c86b51256d5f4d8686183ebcf33252e/jsonpath2/test/jsonpath2_test.py#L712 or make another method and call your match function?

**Comment by dangra** [comment]
Yes, I will once I have a free minute in front of the keyboard. Wait for it
this week. Thanks for the heads up

**Comment by dmlb2000** [comment]
@dangra Forgot to add a bit to the README to document the new method. Could you add that?

**Comment by dangra** [comment]
@dmlb2000 I think I broke your accepted review by force pushing a rebase to cleanup commit history. Feel free to review again and merge. thanks

**Pull request merged**
