### PR TITLE
Implement JSONPath

### LINKED ISSUE #10: Make JSONPath Module
### JSONPath2 version
v0.0.2
### Platform Details
Any
### Scenario:
We should merge in @markborkum jsonpath implementation as a start.
### Steps to Reproduce:
I install jsonpath2 and nothing parses jsonpath
### Expected Result:
A module that parses jsonpath correctly according to specification.
### Actual Result:
an example module.

### PR DESCRIPTION
**Pull request by markborkum**
Copy files from https://github.com/markborkum/pacifica-jsonpath@jsonpath2 and merge conflicts.

### Description

n\a

### Issues Resolved

Fixes #10 

### Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@markborkum Are you ready for me to start making changes? or are you trying to get the pipeline to pass?

**Comment by markborkum** [comment]
@dmlb2000 Yes, please. If you can get it to "test", I'll fix the "lint" warnings/errors.

**Comment by dmlb2000** [comment]
@markborkum The linting will force module renaming, it's important to get the lint stage fixed first.

**Comment by dmlb2000** [comment]
The reason for adding that was when I was looking at other implementations they had some weird expressions.

https://github.com/json-path/JsonPath/blob/master/json-path/src/test/java/com/jayway/jsonpath/FilterTest.java

If you look at some of the tests they have in this test... there's a couple of things.

 * The keys in the json object have dash '-' which isn't allowed in javascript, so not sure what's going on there.
 * They are testing paths like `$[?(1 = '1')]` which is weird but I've seen this in other languages conditionals.

**Comment by dmlb2000** [comment]
@markborkum Can you think of a jsonpath expression where a `VariadicOperatorExpression` would get created with 0 or 1 expressions passed to it?

**Comment by markborkum** [comment]
@dmlb2000 The objects would need to be hand-constructed. Expressions with zero or one operand would be rejected by the parser (e.g., `$[?()]` and `$[?(@["hello"] and)]`).

**Comment by dmlb2000** [comment]
@markborkum Would there be any utility in keeping those code blocks around where `VariadicOperatorExpression` would have 0 or 1 expressions?

**Comment by dmlb2000** [comment]
@markborkum Also, would array slicing like `foo[:2]` be allowed? Seems like it should be.

**Comment by markborkum** [comment]
@dmlb2000 There is no harm in keeping the code as it is. The implementations of the `__evaluate__` and `__jsonpath` methods for the variadic operators are consistent with their specifications.

**Comment by dmlb2000** [comment]
@markborkum Where's the spec you refer too? I'm having issues with array slice.

 * Seems the first integer is always required (I don't think it should be but I'm not finding anything that says otherwise)
 * The second colon requires the step instead of just picking a default (like 1 say)

**Comment by dmlb2000** [comment]
@markborkum I'm thinking we should be similar to the host language as they've got a standard and developers will be used to that kind of array slice behavior.

**Comment by dmlb2000** [comment]
@markborkum The `parser/__init__.py` that wasn't generated by antlr, correct?

We are missing some big blocks in that file and I'm wondering if we are missing a test, `exitObj()` isn't getting called at all. Would we need to have a JSON object as part of an expression in a JSONPath to get that called?

**Comment by dmlb2000** [comment]
@markborkum agreed, the `raise ValueError()` lines should have a `# pragma: no cover` with a consistent reason, 

`# pragma: no cover since AST already handles this case`

**Comment by dmlb2000** [comment]
@markborkum Any last thoughts? I'm good.

**Comment by markborkum** [comment]
@dmlb2000 Ship it!

**Pull request merged**
